name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths:
      - Dockerfile
      - .dockerignore
      - package.json
      - package-lock.json
      - src/**
      - build/**
      - tsconfig.json
  workflow_dispatch: {}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: asbarron  # forced
          password: ${{ secrets.GHCR_TOKEN }} 

      - name: Build and push Docker image with cache
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/asbarron/grow-a-garden-bot:latest
            ghcr.io/asbarron/grow-a-garden-bot:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
