name: Scheduled Stock Check

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes UTC

jobs:
  run-stock-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Run container
        run: |
          docker run --rm \
            -e TARGET_URL=${{ secrets.TARGET_URL }} \
            -e FLAG_KEYWORDS=${{ secrets.FLAG_KEYWORDS }} \
            -e TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }} \
            -e TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }} \
            ghcr.io/${{ secrets.GHCR_USERNAME }}/grow-a-garden-bot:latest
