name: Scheduled Stock Check

on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes UTC
  workflow_dispatch: {}

jobs:
  run-stock-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Create .env file
        run: |
          echo "TARGET_URL=${{ secrets.TARGET_URL }}" >> .env
          echo "FLAG_KEYWORDS='${{ secrets.FLAG_KEYWORDS }}'" >> .env
          echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
          echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> .env

      - name: Run container
        run: |
          docker run --rm --env-file .env ghcr.io/${{ secrets.GHCR_USERNAME }}/grow-a-garden-bot:latest

      - name: Self-ping workflow to re-run
        if: github.event_name == 'schedule'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.SELF_TRIGGER_PAT }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/scheduled-check.yaml/dispatches \
            -d '{"ref":"main"}'
