name: Scheduled Stock Check

on:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes UTC

jobs:
  run-stock-checker:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Debug docker image name
        run: |
            echo "Image: ghcr.io/${{ secrets.GHCR_USERNAME }}/grow-a-garden-bot:latest"
        
      - name: Run container
        env:
          TARGET_URL: ${{ secrets.TARGET_URL }}
          FLAG_KEYWORDS: ${{ secrets.FLAG_KEYWORDS }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          echo "Running container as ${{ secrets.GHCR_USERNAME }}"
          docker run --rm \
            -e TARGET_URL \
            -e FLAG_KEYWORDS \
            -e TELEGRAM_TOKEN \
            -e TELEGRAM_CHAT_ID \
            ghcr.io/${{ secrets.GHCR_USERNAME }}/grow-a-garden-bot:latest
      